import { expect, test } from "@playwright/test";
import { mkdir } from "node:fs/promises";

test.skip(process.env.E2E_DRUM_GEOMETRY !== "1", "Opt-in free geometry checks");
for (const width of [1440, 390]) test(`textured scene, second view, roof edit and alignment ${width}`, async ({ page }) => {
  await page.setViewportSize({ width, height: width === 390 ? 844 : 1000 });
  const errors: string[] = [], generations: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.route("**/api/generate-page", route => { generations.push(route.request().url()); return route.abort(); });
  await page.goto("/sketch/world/ankh/geometry");
  const viewport = page.getByTestId("drum-geometry"), canvas = viewport.locator("canvas");
  await expect(viewport).toHaveAttribute("data-ready", "true");
  await expect.poll(() => viewport.getAttribute("data-camera")).toBe("27.0000,2.2000,9.4000");
  await expect.poll(async () => Number(await viewport.getAttribute("data-textured"))).toBeGreaterThan(100);
  const pixels = () => canvas.evaluate(node => (node as HTMLCanvasElement).toDataURL());
  const first = await pixels();
  const range = await canvas.evaluate(node => {
    const copy = document.createElement("canvas"); copy.width = copy.height = 64;
    const ctx = copy.getContext("2d")!; ctx.drawImage(node as HTMLCanvasElement, 0, 0, 64, 64);
    const values = [...ctx.getImageData(0, 0, 64, 64).data].filter((_, i) => i % 4 !== 3);
    return Math.max(...values) - Math.min(...values);
  });
  expect(range).toBeGreaterThan(70);
  await mkdir(`test-results/drum-geometry-${width}`, { recursive: true });
  await page.screenshot({ path: `test-results/drum-geometry-${width}/01-textured.png` });
  await page.getByRole("slider", { name: "Camera travel", exact: true }).fill("70");
  await expect.poll(() => viewport.getAttribute("data-camera")).toBe("25.6000,2.2000,8.9800");
  await expect.poll(pixels).not.toBe(first);
  await expect(page.getByRole("slider", { name: "Image overlay", exact: true })).toBeDisabled();
  await page.screenshot({ path: `test-results/drum-geometry-${width}/02-second-view.png` });
  const second = await pixels();
  await page.getByRole("button", { name: "Teal roof", exact: true }).click();
  await expect.poll(pixels).not.toBe(second);
  await page.screenshot({ path: `test-results/drum-geometry-${width}/03-teal.png` });
  await page.getByRole("button", { name: "Reset camera", exact: true }).click();
  await expect(viewport).toHaveAttribute("data-ready", "true");
  await page.getByRole("slider", { name: "Image overlay", exact: true }).fill("50");
  await page.getByRole("button", { name: "Alignment points", exact: true }).click();
  await expect(page.getByLabel("Landmark reprojection residuals")).toBeVisible();
  await page.screenshot({ path: `test-results/drum-geometry-${width}/04-alignment.png` });
  await page.getByRole("combobox", { name: "Geometry profile", exact: true }).selectOption("free_camera");
  await expect(viewport).toHaveAttribute("data-ready", "true");
  await expect(page.locator("footer")).toContainText("Rejected: check error increases");
  await page.getByRole("combobox", { name: "Geometry profile", exact: true }).selectOption("original");
  await expect(viewport).toHaveAttribute("data-ready", "true");
  await page.getByRole("checkbox", { name: "Textures", exact: true }).uncheck();
  await expect(viewport).toHaveAttribute("data-textured", "0");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]); expect(generations).toEqual([]);
});
