"""Generate the shared projection golden fixture (committed, hand-verified).

Defines a few hand-authored scenes, runs the Python geometry engine, and writes
packages/config/src/projection-golden.json. Both the pytest gate
(test_geometry.py) and the vitest gate (world-geometry.test.ts) assert their
engine reproduces this file — so a TS/Py divergence fails the parity gate.

Re-run only when the projection spec intentionally changes:
    python apps/modal-backend/tests/world_bench/_gen_projection_golden.py
Then eyeball the bins (h_pos/v_pos/size) + culled set make physical sense.
"""
from __future__ import annotations

import json
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from providers import geometry

_HALF_PI = math.pi / 2.0


def _ent(eid: str, x: float, y: float, height: float, fw: float = 6.0, elevation: float = 0.0):
    e = {
        "id": eid,
        "label": eid,
        "pos": {"x": x, "y": y},
        "height": height,
        "footprint": {"w": fw, "d": fw},
    }
    if elevation:  # omit the key for ground entities (default 0 == on the ground)
        e["elevation"] = elevation
    return e


SCENES = [
    {
        "name": "flanks-east-fov90",
        "observer": {"pos": {"x": 0, "y": 0}, "eye_height": 1.7, "gaze": 0.0, "fov": math.pi / 2},
        "entities": [
            _ent("Near", 10, 0, 8),
            _ent("Center", 30, 0, 10),
            _ent("Right", 40, 30, 10),
            _ent("Left", 40, -30, 10),
            _ent("Behind", -30, 0, 10),
        ],
    },
    {
        # gaze = +pi/2 → heading +y, which is SOUTH in image coords (+y down).
        # Facing south: east (+x) renders on the LEFT, west (-x) on the RIGHT.
        "name": "south-fov60-tall",
        "observer": {"pos": {"x": 0, "y": 0}, "eye_height": 1.7, "gaze": _HALF_PI, "fov": math.pi / 3},
        "entities": [
            _ent("Ahead", 0, 40, 10),
            _ent("EastOnLeft", 20, 40, 10),
            _ent("WestOnRight", -20, 40, 10),
            _ent("TallClose", 0, 10, 20),
            _ent("BehindNorth", 0, -40, 10),
            _ent("FarAhead", 0, 150, 10),
        ],
    },
    {
        # Camera tilted UP (+pitch) at a tall tower, with a lantern hanging
        # ELEVATED off the ground. Exercises the Z fields: pitch drops the horizon
        # (grounded pieces sit lower), elevation lifts the lantern higher.
        "name": "pitch-up-elevated",
        "observer": {"pos": {"x": 0, "y": 0}, "eye_height": 1.7, "gaze": 0.0, "pitch": 0.3, "fov": math.pi / 2},
        "entities": [
            _ent("Tower", 25, 0, 30),
            _ent("Lantern", 12, 4, 1, fw=2.0, elevation=3.0),
            _ent("Cobble", 15, 0, 1),
        ],
    },
]

ASPECT = 16.0 / 9.0


def _round_floats(p: dict) -> dict:
    out = {}
    for k, v in p.items():
        out[k] = round(v, 9) if isinstance(v, float) else v
    return out


def build() -> dict:
    scenes_out = []
    for sc in SCENES:
        projected = [_round_floats(p) for p in geometry.project_scene(sc["entities"], sc["observer"], ASPECT)]
        visible_ids = {p["id"] for p in projected}
        culled = sorted(e["id"] for e in sc["entities"] if e["id"] not in visible_ids)
        scenes_out.append(
            {
                "name": sc["name"],
                "observer": sc["observer"],
                "entities": sc["entities"],
                "expected": projected,
                "culled": culled,
            }
        )
    return {
        "_comment": "Shared 2.5D projection golden. Generated by tests/world_bench/_gen_projection_golden.py; both the pytest + vitest geometry gates must reproduce `expected`/`culled`. Hand-verify bins on regen.",
        "aspect": ASPECT,
        "scenes": scenes_out,
    }


def main() -> None:
    out_path = Path(__file__).resolve().parents[4] / "packages/config/src/projection-golden.json"
    out_path.write_text(json.dumps(build(), indent=2) + "\n")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
