"""Generate the cross-language projection parity-fuzz corpus (committed).

A SEEDED random sweep of scenes (varied observer poses, FOVs, aspects, entity
placements incl. behind/out-of-FOV culls), run through the Python geometry
engine. The output (packages/config/src/projection-fuzz.json) is the differential
oracle: the vitest gate (world-geometry.fuzz.test.ts) runs the TS engine on the
SAME inputs and must reproduce every projection within 1e-6 — so any TS/Py drift
on any of these inputs fails the gate. test_geometry_fuzz.py re-runs this with
the same seed and asserts the committed file is reproducible (Python is pinned).

Re-run only when the projection spec intentionally changes:
    python apps/modal-backend/tests/world_bench/_gen_parity_fuzz.py
"""
from __future__ import annotations

import json
import math
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from providers import geometry

SEED = 20260606
N_SCENES = 80
_ASPECTS = [16.0 / 9.0, 9.0 / 16.0, 1.0, 4.0 / 3.0]


def _round(v):
    return round(v, 9) if isinstance(v, float) else v


def build() -> dict:
    rng = random.Random(SEED)
    scenes = []
    for _ in range(N_SCENES):
        observer = {
            "pos": {"x": round(rng.uniform(-100, 100), 4), "y": round(rng.uniform(-100, 100), 4)},
            "eye_height": round(rng.uniform(1.0, 6.0), 4),
            "gaze": round(rng.uniform(-math.pi, math.pi), 6),
            "fov": round(rng.uniform(0.6, 2.4), 6),
        }
        aspect = rng.choice(_ASPECTS)
        n_ent = rng.randint(2, 6)
        entities = []
        for j in range(n_ent):
            fw = round(rng.uniform(0.5, 20.0), 4)
            # 70%: place inside the FOV cone at a random distance (likely visible
            # → exercises the float math); 30%: fully random (exercises culling).
            if rng.random() < 0.7:
                bearing = observer["gaze"] + rng.uniform(-0.45, 0.45) * observer["fov"]
                dist = rng.uniform(3.0, 180.0)
                ex = observer["pos"]["x"] + dist * math.cos(bearing)
                ey = observer["pos"]["y"] + dist * math.sin(bearing)
            else:
                ex = rng.uniform(-200, 200)
                ey = rng.uniform(-200, 200)
            entities.append(
                {
                    "id": f"e{j}",
                    "label": f"e{j}",
                    "pos": {"x": round(ex, 4), "y": round(ey, 4)},
                    "height": round(rng.uniform(0.5, 40.0), 4),
                    "footprint": {"w": fw, "d": fw},
                }
            )
        projected = [
            {k: _round(v) for k, v in p.items()}
            for p in geometry.project_scene(entities, observer, aspect)
        ]
        scenes.append(
            {"observer": observer, "aspect": aspect, "entities": entities, "expected": projected}
        )
    return {
        "_comment": "Cross-language projection parity-fuzz oracle. Generated by tests/world_bench/_gen_parity_fuzz.py (seed pinned). The vitest TS engine must reproduce every `expected` within 1e-6.",
        "seed": SEED,
        "n_scenes": N_SCENES,
        "scenes": scenes,
    }


def main() -> None:
    out = Path(__file__).resolve().parents[4] / "packages/config/src/projection-fuzz.json"
    out.write_text(json.dumps(build(), separators=(",", ":")) + "\n")
    total = sum(len(s["expected"]) for s in build()["scenes"])
    print(f"wrote {out} — {N_SCENES} scenes, {total} visible projections")


if __name__ == "__main__":
    main()
